blank_issues_enabled: true
contact_links:
 - name: Documentation Link
   url: https://github.com/SLINGhub/MSTemplate_Creator/tree/master/docs
   about: Link to the documentation of this software.
 - name: Bug Report Guidelines
   url: https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
   about: Link to help you write a good bug report.
 - name: Feature Request Guidelines
   url: https://github.com/rstudio/rstudio/wiki/Writing-Good-Feature-Requests
   about: Link to help you write a good bug feature request.
